package view;

import controller.UsuarioDAO;
import controller.LoginDAO;
import controller.ClienteDAO;
import controller.VeiculoDAO;
import controller.ServicoDAO;

import javax.swing.JOptionPane;
import java.util.ArrayList;

import model.Cliente;
import model.Usuario;
import model.Veiculo;
import model.Servico;

public class ReiForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReiForm.class.getName());

    private UsuarioDAO dao = new UsuarioDAO();
    private LoginDAO log = new LoginDAO();
    private ClienteDAO cl = new ClienteDAO();
    private VeiculoDAO vw = new VeiculoDAO();
    private ServicoDAO sd = new ServicoDAO();
    
    public ReiForm() {
        
        initComponents();
        
        this.setTitle("Bem-vindo ao ReiDaEspuma App!");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        carregarTipoServico();
        
        jTabbedPane1.addChangeListener(e -> {
        int abaSelecionada = jTabbedPane1.getSelectedIndex();
        
        switch (abaSelecionada) {
            case 3 -> carregarClientes();   // Aba Cadastro Veículo
            case 4 -> carregarVeiculo();   // Aba Cadastro Serviço
            case 5 -> carregarTabela();    // Aba Pesquisa Tabela
        }
    });
    }
    
    //ComboBox - Dono do Veículo
    public void carregarClientes(){
        
        ClienteDAO cl = new ClienteDAO();
        ArrayList<Cliente> lista = cl.listar();
        
        cbCliente.removeAllItems();
        
        for(Cliente c : lista){
            cbCliente.addItem(c);   
        }
    }
    //ComboBox - Serviço pegando a Placa
    public void carregarVeiculo(){
        
        VeiculoDAO vw = new VeiculoDAO();
        ArrayList<Veiculo> lista = vw.listar();
        
        cbVeiculo.removeAllItems();
        
        for(Veiculo v : lista){
            cbVeiculo.addItem(v);
        }
 }     
   //ComboBox - Serviços
    public void carregarTipoServico(){
        
        cbTipoServico.removeAllItems();
        cbTipoServico.addItem("Lavagem Simples - R$ 100,00");
        cbTipoServico.addItem("Lavagem Completa - R$ 150,00");
        cbTipoServico.addItem("Lavagem de Luxo - R$ 200,00");
    }
    // TABELA
    public void carregarTabela() {

    ServicoDAO sd = new ServicoDAO();

    EspumaTableModel modelo =
            new EspumaTableModel(sd.listarTabela());

    tbDados.setModel(modelo);
}
    // Pesquisa
    public void carregarPesquisa(String texto) {

    ServicoDAO sd = new ServicoDAO();

    EspumaTableModel modelo =
            new EspumaTableModel(sd.pesquisar(texto));

    tbDados.setModel(modelo);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNomeEmpregado = new javax.swing.JLabel();
        txtNomeEmpregado = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailEmpregado = new javax.swing.JTextField();
        lblSenhaEmpregado = new javax.swing.JLabel();
        btnCadastroEmpregado = new javax.swing.JButton();
        pwdSenhaEmpregado = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        lblEmailLogin = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnAcessar = new javax.swing.JButton();
        pwdSenha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCadastroNovoCliente = new javax.swing.JLabel();
        lblDadosClientes = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btnCadastrarCliente = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblNascimento = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        lblObsCliente = new javax.swing.JLabel();
        txtObsCliente = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblObsVeiculo = new javax.swing.JLabel();
        txtObsVeiculo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        BtnCadastrarVeiculo = new javax.swing.JButton();
        btnCancelarVeiculo = new javax.swing.JButton();
        btnAtualizarVeiculo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbVeiculo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbTipoServico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        chkAr = new javax.swing.JCheckBox();
        chkCouro = new javax.swing.JCheckBox();
        btnRegistrarServico = new javax.swing.JButton();
        btnAtualizarServico = new javax.swing.JButton();
        chkCera = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        lblClientesReiDaEspuma = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        lblExplicação = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Cadastro do Empregado");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Dados do Empregado");

        lblNomeEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeEmpregado.setText("Nome");

        txtNomeEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("E-mail");

        txtEmailEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSenhaEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenhaEmpregado.setText("Senha");

        btnCadastroEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCadastroEmpregado.setText("Cadastrar");
        btnCadastroEmpregado.addActionListener(this::btnCadastroEmpregadoActionPerformed);

        pwdSenhaEmpregado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomeEmpregado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSenhaEmpregado)))
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmailEmpregado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtNomeEmpregado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdSenhaEmpregado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastroEmpregado)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addGap(34, 34, 34)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeEmpregado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblSenhaEmpregado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdSenhaEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Usuário", jPanel1);

        lblEmailLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEmailLogin.setText("E-mail:");

        txtEmailLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSenha.setText("Senha:");

        btnAcessar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAcessar.setText("Acessar");
        btnAcessar.addActionListener(this::btnAcessarActionPerformed);

        pwdSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_200.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(lblEmailLogin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(lblSenha))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addComponent(lblEmailLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel2);

        lblCadastroNovoCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastroNovoCliente.setText("Cadastro Novo Cliente");

        lblDadosClientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDadosClientes.setText("Dados Do Cliente");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome Completo");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone");

        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastrarCliente.setText("Cadastrar");
        btnCadastrarCliente.addActionListener(this::btnCadastrarClienteActionPerformed);

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCPF.setText("CPF");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEndereco.setText("Endereço");

        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNascimento.setText("Data de Nascimento");

        txtNascimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblObsCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObsCliente.setText("Observação");

        txtObsCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpar.setText("Limpar Dados");
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblTelefone)
                            .addComponent(lblCPF))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObsCliente)
                            .addComponent(lblNascimento)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtObsCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(txtNascimento, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(73, 73, 73)
                                .addComponent(btnCadastrarCliente)))
                        .addGap(0, 79, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDadosClientes)
                        .addGap(50, 50, 50))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblCadastroNovoCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCadastroNovoCliente)
                .addGap(82, 82, 82)
                .addComponent(lblDadosClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(lblEndereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTelefone))
                    .addComponent(lblNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblObsCliente)
                    .addComponent(lblCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtObsCliente)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Cadastro Cliente", jPanel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro Novo Veículo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Dados do Veículo");

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPlaca.setText("Placa");

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarca.setText("Marca");

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCor.setText("Cor");

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblModelo.setText("Modelo");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblObsVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblObsVeiculo.setText("Observação");

        txtObsVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Proprietário");

        cbCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        BtnCadastrarVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCadastrarVeiculo.setText("Cadastrar");
        BtnCadastrarVeiculo.addActionListener(this::BtnCadastrarVeiculoActionPerformed);

        btnCancelarVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelarVeiculo.setText("Cancelar");
        btnCancelarVeiculo.addActionListener(this::btnCancelarVeiculoActionPerformed);

        btnAtualizarVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtualizarVeiculo.setText("Atualizar");
        btnAtualizarVeiculo.addActionListener(this::btnAtualizarVeiculoActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlaca)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMarca)
                                    .addComponent(lblModelo)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCor)
                                    .addComponent(jLabel2))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblObsVeiculo)
                                    .addComponent(txtObsVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(btnCancelarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnAtualizarVeiculo)
                                .addGap(32, 32, 32)
                                .addComponent(BtnCadastrarVeiculo))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblObsVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObsVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCor)
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Veículo", jPanel4);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cadastro de Serviço");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Dados do Serviço");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Veículo");

        cbVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tipo De Serviço");

        cbTipoServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Adicionais");

        chkAr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAr.setText("Higienização de Ar-Condicionado(R$ 75,00)");

        chkCouro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCouro.setText("Hidratação de Couro(R$ 30,00)");

        btnRegistrarServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarServico.setText("Registrar");
        btnRegistrarServico.addActionListener(this::btnRegistrarServicoActionPerformed);

        btnAtualizarServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAtualizarServico.setText("Atualizar");
        btnAtualizarServico.addActionListener(this::btnAtualizarServicoActionPerformed);

        chkCera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCera.setText("Cera(R$ 20,00)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtualizarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnRegistrarServico)
                .addGap(96, 96, 96))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbTipoServico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbVeiculo, javax.swing.GroupLayout.Alignment.LEADING, 0, 270, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkAr))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkCouro))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkCera)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkCera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCouro)
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarServico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Serviço", jPanel5);

        lblClientesReiDaEspuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblClientesReiDaEspuma.setText("Tabela de Clientes");

        lblPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPesquisa.setText("Pesquisar");

        txtPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisa.addActionListener(this::txtPesquisaActionPerformed);

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDados);

        lblExplicação.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExplicação.setText("Para Atualização dos dados: Clicar na linha selecionada e voltar no Cadastro Serviço");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(lblPesquisa))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(lblClientesReiDaEspuma))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblExplicação)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblClientesReiDaEspuma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExplicação)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisa Tabela", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtTelefone.setText("");
        txtCPF.setText("");
        txtEndereco.setText("");
        txtNascimento.setText("");
        txtObsCliente.setText("");
        
        JOptionPane.showMessageDialog(null, "Dados limpados com sucesso!");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastroEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroEmpregadoActionPerformed
        Usuario u = new Usuario();
        
        u.setNome(txtNomeEmpregado.getText());
        u.setEmail(txtEmailEmpregado.getText());
        u.setSenha(String.valueOf(pwdSenhaEmpregado.getPassword()));
        
        dao.inserir(u);
        JOptionPane.showMessageDialog(
                null,
                "Empregado cadastrado com sucesso!"
        );
    }//GEN-LAST:event_btnCadastroEmpregadoActionPerformed

    private void btnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessarActionPerformed
        
        Usuario u = new Usuario();

    u.setEmail(txtEmailLogin.getText());
    u.setSenha(String.valueOf(pwdSenha.getPassword()));

    LoginDAO log = new LoginDAO();

    if(
        txtEmailLogin.getText().isEmpty() ||
        String.valueOf(pwdSenha.getPassword()).isEmpty()
    ){

        JOptionPane.showMessageDialog(
                null,
                "Preencha todos os campos!"
        );

    } else {

        if(log.login(u)){

            JOptionPane.showMessageDialog(
                    null,
                    "Login realizado com sucesso!"
            );

        } else {

            JOptionPane.showMessageDialog(
                    null,
                    "Email ou senha inválidos!"
            );
        }
    }
    }//GEN-LAST:event_btnAcessarActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        
        Cliente c = new Cliente();
        
        c.setNome(txtNome.getText());
        c.setTelefone(txtTelefone.getText());
        c.setCpf(txtCPF.getText());
        c.setEndereco(txtEndereco.getText());
        c.setNascimento(txtNascimento.getText());
        c.setObservacao(txtObsCliente.getText());
        
        ClienteDAO cl = new ClienteDAO();
        
        if(
        txtNome.getText().isEmpty() ||
        txtTelefone.getText().isEmpty() ||
        txtCPF.getText().isEmpty()
    ){

        JOptionPane.showMessageDialog(
                null,
                "Preencha os campos obrigatórios!"
        );
        } else {
            cl.inserir(c);
            
             JOptionPane.showMessageDialog(
                null,
                "Cliente cadastrado com sucesso!"
        );
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void BtnCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarVeiculoActionPerformed
        
        Cliente clienteSelecionado = (Cliente) cbCliente.getSelectedItem();

    if (clienteSelecionado == null) {
        JOptionPane.showMessageDialog(null, "Selecione um proprietário!");
        return;
    }

    if (txtPlaca.getText().isEmpty() || txtMarca.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
        return;
    }

    Veiculo v = new Veiculo();
    v.setPlaca(txtPlaca.getText());
    v.setMarca(txtMarca.getText());
    v.setModelo(txtModelo.getText());
    v.setCor(txtCor.getText());
    v.setObservacao(txtObsVeiculo.getText());
    v.setIdCliente(clienteSelecionado.getId());
    
    VeiculoDAO vw = new VeiculoDAO();
    vw.inserir(v);

    JOptionPane.showMessageDialog(null, "Veículo cadastrado com sucesso!");
    }//GEN-LAST:event_BtnCadastrarVeiculoActionPerformed

    private void btnCancelarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVeiculoActionPerformed
        
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCor.setText("");
        txtObsVeiculo.setText("");
        cbCliente.setSelectedIndex(0);
        
        JOptionPane.showMessageDialog(null,"Registro Cancelado!");
    }//GEN-LAST:event_btnCancelarVeiculoActionPerformed

    private void btnRegistrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarServicoActionPerformed
        
        Veiculo veiculoSelecionado = (Veiculo) cbVeiculo.getSelectedItem();
        
        if (veiculoSelecionado == null) {
            JOptionPane.showMessageDialog(null, "Selecione um veículo!");
            return;
    }
        //Calculo valor total
        
        double valorTotal = 0;
        String tipoSelecionado = (String) cbTipoServico.getSelectedItem();
        if (tipoSelecionado.contains("Simples")) {
        valorTotal = 100.00;
    } else if (tipoSelecionado.contains("Completa")) {
        valorTotal = 150.00;
    } else if (tipoSelecionado.contains("Luxo")) {
        valorTotal = 200.00;
    }

    if (chkCera.isSelected())    valorTotal += 20.00;
    if (chkAr.isSelected())      valorTotal += 75.00;
    if (chkCouro.isSelected())   valorTotal += 30.00;
        
        Servico s = new Servico();
        s.setTipoServico(tipoSelecionado);
         s.setCera(chkCera.isSelected());
         s.setHigienizacaoAr(chkAr.isSelected());
         s.setHidratacaoCouro(chkCouro.isSelected());
         s.setValorTotal(valorTotal);
         s.setIdVeiculo(veiculoSelecionado.getId());
         
         ServicoDAO sd = new ServicoDAO();
         sd.inserir(s);
         
         JOptionPane.showMessageDialog(null, 
        "Serviço registrado!\nValor Total: R$ " + String.format("%.2f", valorTotal));
    }//GEN-LAST:event_btnRegistrarServicoActionPerformed

    private void btnAtualizarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarServicoActionPerformed
        
        int linhaSelecionada = tbDados.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(null, "Selecione um serviço na tabela para atualizar!");
        return;
    }

    Veiculo veiculoSelecionado = (Veiculo) cbVeiculo.getSelectedItem();

    if (veiculoSelecionado == null) {
        JOptionPane.showMessageDialog(null, "Selecione um veículo!");
        return;
    }

    double valorTotal = 0;
    String tipoSelecionado = (String) cbTipoServico.getSelectedItem();

    if (tipoSelecionado.contains("Simples")) {
        valorTotal = 100.00;
    } else if (tipoSelecionado.contains("Completa")) {
        valorTotal = 150.00;
    } else if (tipoSelecionado.contains("Luxo")) {
        valorTotal = 200.00;
    }

    if (chkCera.isSelected())   valorTotal += 20.00;
    if (chkAr.isSelected())     valorTotal += 75.00;
    if (chkCouro.isSelected())  valorTotal += 30.00;

    Servico s = new Servico();
    s.setId(((EspumaTableModel) tbDados.getModel()).getIdAt(linhaSelecionada));
    s.setTipoServico(tipoSelecionado);
    s.setCera(chkCera.isSelected());
    s.setHigienizacaoAr(chkAr.isSelected());
    s.setHidratacaoCouro(chkCouro.isSelected());
    s.setValorTotal(valorTotal);
    s.setIdVeiculo(veiculoSelecionado.getId());

    ServicoDAO sd = new ServicoDAO();
    sd.atualizar(s);

    JOptionPane.showMessageDialog(null,
        "Serviço atualizado!\nValor Total: R$ " + String.format("%.2f", valorTotal));

    carregarTabela();
    }//GEN-LAST:event_btnAtualizarServicoActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        carregarPesquisa(txtPesquisa.getText());
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnAtualizarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarVeiculoActionPerformed
        
        Veiculo veiculoSelecionado =
            (Veiculo) cbVeiculo.getSelectedItem();

    Cliente clienteSelecionado =
            (Cliente) cbCliente.getSelectedItem();

    if (veiculoSelecionado == null) {

        JOptionPane.showMessageDialog(
                null,
                "Selecione um veículo!"
        );

        return;
    }

    Veiculo v = new Veiculo();

    // MUITO IMPORTANTE
    v.setId(veiculoSelecionado.getId());

    v.setPlaca(txtPlaca.getText());
    v.setMarca(txtMarca.getText());
    v.setModelo(txtModelo.getText());
    v.setCor(txtCor.getText());
    v.setObservacao(txtObsVeiculo.getText());

    v.setIdCliente(clienteSelecionado.getId());

    VeiculoDAO vd = new VeiculoDAO();

    vd.atualizar(v);

    JOptionPane.showMessageDialog(
            null,
            "Veículo atualizado!"
    );
    }//GEN-LAST:event_btnAtualizarVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarVeiculo;
    private javax.swing.JButton btnAcessar;
    private javax.swing.JButton btnAtualizarServico;
    private javax.swing.JButton btnAtualizarVeiculo;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastroEmpregado;
    private javax.swing.JButton btnCancelarVeiculo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRegistrarServico;
    private javax.swing.JComboBox<Cliente> cbCliente;
    private javax.swing.JComboBox<String> cbTipoServico;
    private javax.swing.JComboBox<Veiculo> cbVeiculo;
    private javax.swing.JCheckBox chkAr;
    private javax.swing.JCheckBox chkCera;
    private javax.swing.JCheckBox chkCouro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastroNovoCliente;
    private javax.swing.JLabel lblClientesReiDaEspuma;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDadosClientes;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailLogin;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblExplicação;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeEmpregado;
    private javax.swing.JLabel lblObsCliente;
    private javax.swing.JLabel lblObsVeiculo;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaEmpregado;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JPasswordField pwdSenhaEmpregado;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtEmailEmpregado;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEmpregado;
    private javax.swing.JTextField txtObsCliente;
    private javax.swing.JTextField txtObsVeiculo;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
